import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import PrelineScript from "./Preline/PrelineScript";
import Footer from "./Components/Footer";
import Navv from "./Components/Navv";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`flex flex-col min-h-screen ${inter.className}`}>
        <Navv />

        <div className="flex-grow">{children}</div>
        <Footer />
        <PrelineScript />
      </body>
    </html>
  );
}
